application: devfest-cordoval
version: 7
runtime: php
api_version: 1

handlers:
- url: /bundles
  static_dir: web/bundles

- url: /app_dev\.php.*
  script: web/app_dev.php

- url: .*
  script: web/app.php

env_variables:
  DISABLE_FUNCTIONS: true